//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorageClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dataStorageEntity : DbContext
    {
        public dataStorageEntity()
            : base("name=dataStorageEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<conductor> conductor { get; set; }
        public DbSet<dispatcher> dispatcher { get; set; }
        public DbSet<driver> driver { get; set; }
        public DbSet<route> route { get; set; }
        public DbSet<trip> trip { get; set; }
    }
}
