//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorageClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public driver()
        {
            this.trip = new HashSet<trip>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int trip_count { get; set; }
    
        public virtual ICollection<trip> trip { get; set; }
    }
}
