//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorageClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public Nullable<int> stop_count { get; set; }
        public int Route_route_number { get; set; }
        public int Dispatcher_id { get; set; }
        public int conductor_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
        public Nullable<int> passenger_count { get; set; }
        public int driver_id { get; set; }
    
        public virtual conductor conductor { get; set; }
        public virtual dispatcher dispatcher { get; set; }
        public virtual driver driver { get; set; }
        public virtual route route { get; set; }
    }
}
